### ISSUE TITLE
Not able to download dataset.

### ISSUE THREAD

**Issue by ParvezAlam123** [SceneFun3D/scenefun3d#6]
Dear team,
I tried to download dataset but I am getting empty folders only, no data files ?? Can anyone help ?

**Comment by AlexDelitzas** [comment]
Hi @ParvezAlam123  , 

Data download appears to be functioning correctly on our end. Could you please provide some more details about the issue you're facing? Thanks!

**Comment by ParvezAlam123** [comment]
I used the following  steps:
git clone https://github.com/SceneFun3D/scenefun3d.git
cd scenefun3d 

Create virtual environment:


conda create --name scenefun3d python=3.8
conda activate scenefun3d
pip install -r requirements.txt

 then I used ;
 python3 -m data_downloader.data_asset_download --split train_val_set --download_dir data/ --dataset_assets laser_scan_5mm


but in my data folder I am getting empty folders only. 
![Screenshot from 2024-12-05 12-14-31](https://github.com/user-attachments/assets/aa19fbb2-348b-4103-963c-3ccd35fef76a)
![Screenshot from 2024-12-05 12-14-38](https://github.com/user-attachments/assets/5eac3cea-dece-463d-a089-7de3148f0060)

**Comment by ParvezAlam123** [comment]
I resolved the issue using 
sudo apt install curl

thank you for help.

**Comment by AlexDelitzas** [comment]
That's great to hear! Thanks for posting the solution :)
